[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[build-dependencies]
dotenv = "0.15"

[dependencies]
dialoguer = "0.11"
walkdir = "2.5"
colored = "2.1"
indicatif = "0.17"
rayon = "1.10"
ignore = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
regex = "1.10"

[dev-dependencies]
tempfile = "3.10"
